/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';

// Create Virtual Routes

const Demo6LazyImport = createFileRoute('/demo6')();
const Demo5LazyImport = createFileRoute('/demo5')();
const Demo4LazyImport = createFileRoute('/demo4')();
const Demo3LazyImport = createFileRoute('/demo3')();
const Demo2LazyImport = createFileRoute('/demo2')();
const IndexLazyImport = createFileRoute('/')();

// Create/Update Routes

const Demo6LazyRoute = Demo6LazyImport.update({
  id: '/demo6',
  path: '/demo6',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/demo6.lazy').then(d => d.Route));

const Demo5LazyRoute = Demo5LazyImport.update({
  id: '/demo5',
  path: '/demo5',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/demo5.lazy').then(d => d.Route));

const Demo4LazyRoute = Demo4LazyImport.update({
  id: '/demo4',
  path: '/demo4',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/demo4.lazy').then(d => d.Route));

const Demo3LazyRoute = Demo3LazyImport.update({
  id: '/demo3',
  path: '/demo3',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/demo3.lazy').then(d => d.Route));

const Demo2LazyRoute = Demo2LazyImport.update({
  id: '/demo2',
  path: '/demo2',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/demo2.lazy').then(d => d.Route));

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then(d => d.Route));

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/demo2': {
      id: '/demo2';
      path: '/demo2';
      fullPath: '/demo2';
      preLoaderRoute: typeof Demo2LazyImport;
      parentRoute: typeof rootRoute;
    };
    '/demo3': {
      id: '/demo3';
      path: '/demo3';
      fullPath: '/demo3';
      preLoaderRoute: typeof Demo3LazyImport;
      parentRoute: typeof rootRoute;
    };
    '/demo4': {
      id: '/demo4';
      path: '/demo4';
      fullPath: '/demo4';
      preLoaderRoute: typeof Demo4LazyImport;
      parentRoute: typeof rootRoute;
    };
    '/demo5': {
      id: '/demo5';
      path: '/demo5';
      fullPath: '/demo5';
      preLoaderRoute: typeof Demo5LazyImport;
      parentRoute: typeof rootRoute;
    };
    '/demo6': {
      id: '/demo6';
      path: '/demo6';
      fullPath: '/demo6';
      preLoaderRoute: typeof Demo6LazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute;
  '/demo2': typeof Demo2LazyRoute;
  '/demo3': typeof Demo3LazyRoute;
  '/demo4': typeof Demo4LazyRoute;
  '/demo5': typeof Demo5LazyRoute;
  '/demo6': typeof Demo6LazyRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute;
  '/demo2': typeof Demo2LazyRoute;
  '/demo3': typeof Demo3LazyRoute;
  '/demo4': typeof Demo4LazyRoute;
  '/demo5': typeof Demo5LazyRoute;
  '/demo6': typeof Demo6LazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexLazyRoute;
  '/demo2': typeof Demo2LazyRoute;
  '/demo3': typeof Demo3LazyRoute;
  '/demo4': typeof Demo4LazyRoute;
  '/demo5': typeof Demo5LazyRoute;
  '/demo6': typeof Demo6LazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/demo2' | '/demo3' | '/demo4' | '/demo5' | '/demo6';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/demo2' | '/demo3' | '/demo4' | '/demo5' | '/demo6';
  id: '__root__' | '/' | '/demo2' | '/demo3' | '/demo4' | '/demo5' | '/demo6';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  Demo2LazyRoute: typeof Demo2LazyRoute;
  Demo3LazyRoute: typeof Demo3LazyRoute;
  Demo4LazyRoute: typeof Demo4LazyRoute;
  Demo5LazyRoute: typeof Demo5LazyRoute;
  Demo6LazyRoute: typeof Demo6LazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  Demo2LazyRoute: Demo2LazyRoute,
  Demo3LazyRoute: Demo3LazyRoute,
  Demo4LazyRoute: Demo4LazyRoute,
  Demo5LazyRoute: Demo5LazyRoute,
  Demo6LazyRoute: Demo6LazyRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demo2",
        "/demo3",
        "/demo4",
        "/demo5",
        "/demo6"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/demo2": {
      "filePath": "demo2.lazy.tsx"
    },
    "/demo3": {
      "filePath": "demo3.lazy.tsx"
    },
    "/demo4": {
      "filePath": "demo4.lazy.tsx"
    },
    "/demo5": {
      "filePath": "demo5.lazy.tsx"
    },
    "/demo6": {
      "filePath": "demo6.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
